In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
df=pd.read_csv('C:/Users/abcpa/OneDrive/Escritorio/Maestria Ingenieria Y Analitica de datos/Modelado y simulacion/Datos/clasificacion.txt',sep='\t')
df.head(95)

,ID Caso,Clase_Vino,Alcohol,Acido_Malico,Cenizas,Alcalinidad_Cenizas,Magnesio,Fenoles_Totales,Flavanoides,Fenoles_No_Flavanoides,Protoantocianinas,Intensidad_Color,Matiz,OD280_OD315_de_los_vinos_diluidos,Prolina
0,1,1,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,2,1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,3,1,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,4,1,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,5,1,13.24,NaN,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,175,3,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,176,3,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,177,3,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,178,3,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560
178,179,3,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

### Inspeccionando el conjunto de datos

In [ ]:
df.shape
df.info()

### Calculando estadÃ­sticas descriptivas

In [3]:
print('------------------------------------------------')
print('CALCULO DE ESTADISTICAS PARA LA VARIABLE CENIZAS')
print(f'El maximo de la variable cenizas es igual a {df.Cenizas.max()}')
print(f'El minimo de la variable cenizas es igual a {df.Cenizas.min()}')
print(f'La media de la variable cenizas es igual a {df.Cenizas.mean(),2}')
print(f'La desviacion estandar de la variable cenizas es igual a {df.Cenizas.std(),2}')
print(f'La varianza de la variable cenizas es igual a {df.Cenizas.var(),2}')

------------------------------------------------
CALCULO DE ESTADISTICAS PARA LA VARIABLE CENIZAS
El maximo de la variable cenizas es igual a 3.23
El minimo de la variable cenizas es igual a 1.36
La media de la variable cenizas es igual a (np.float64(2.364602272727273), 2)
La desviacion estandar de la variable cenizas es igual a (np.float64(0.2733994686909971), 2)
La varianza de la variable cenizas es igual a (np.float64(0.0747472694805195), 2)

In [5]:
print('------------------------------------------------')
print('ESTADISTICAS RESUMIDAS')
df.describe(include='all')
df.head(10)
len(df) 
df.tail(5) 
df.columns 
df['Alcohol'] 
df['Alcohol'][:5] 
df['Alcohol'][5] 
df[['Prolina', 'Alcohol']][:5] 
df['Clase_Vino'].value_counts() 
#df['Clase_Vino'].unique()

------------------------------------------------
ESTADISTICAS RESUMIDAS

Clase_Vino
2    71
1    59
3    49
Name: count, dtype: int64

### CÃ¡lculo de Correlaciones

In [ ]:
df.corr(method=)